<?php
/**
 * Title: Katalyst Partners
 * Slug: katalyst/partners
 * Categories: katalyst-sections, featured
 * Description: Editable partner and funder section.
 * Viewport Width: 1360
 */
?>
<!-- wp:group {"tagName":"section","anchor":"partner","className":"cs bordered","layout":{"type":"default"}} -->
<section id="partner" class="wp-block-group cs bordered"><!-- wp:group {"className":"inner","layout":{"type":"default"}} --><div class="wp-block-group inner"><!-- wp:group {"className":"s-head reveal-up","layout":{"type":"flex","verticalAlignment":"center"}} --><div class="wp-block-group s-head reveal-up"><!-- wp:paragraph {"className":"s-num"} --><p class="s-num">06 · Partner</p><!-- /wp:paragraph --><!-- wp:heading {"level":2,"className":"s-h"} --><h2 class="s-h">Wer KATALYST möglich macht.</h2><!-- /wp:heading --><!-- wp:html --><span class="s-line"></span><!-- /wp:html --></div><!-- /wp:group --><!-- wp:group {"className":"partners reveal-up","layout":{"type":"default"}} --><div class="wp-block-group partners reveal-up"><!-- wp:group {"className":"p","layout":{"type":"constrained"}} --><div class="wp-block-group p"><!-- wp:paragraph --><p>HS Kempten</p><!-- /wp:paragraph --></div><!-- /wp:group --><!-- wp:group {"className":"p","layout":{"type":"constrained"}} --><div class="wp-block-group p"><!-- wp:paragraph --><p>Partner-Logo</p><!-- /wp:paragraph --></div><!-- /wp:group --><!-- wp:group {"className":"p","layout":{"type":"constrained"}} --><div class="wp-block-group p"><!-- wp:paragraph --><p>Partner-Logo</p><!-- /wp:paragraph --></div><!-- /wp:group --><!-- wp:group {"className":"p","layout":{"type":"constrained"}} --><div class="wp-block-group p"><!-- wp:paragraph --><p>Partner-Logo</p><!-- /wp:paragraph --></div><!-- /wp:group --><!-- wp:group {"className":"p","layout":{"type":"constrained"}} --><div class="wp-block-group p"><!-- wp:paragraph --><p>Partner-Logo</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group --><!-- wp:group {"className":"funder reveal-up","layout":{"type":"grid","columnCount":3,"minimumColumnWidth":"14rem"}} --><div class="wp-block-group funder reveal-up"><!-- wp:image {"sizeSlug":"medium","className":"ph"} --><figure class="wp-block-image size-medium ph"><img alt=""/></figure><!-- /wp:image --><!-- wp:group {"className":"t","layout":{"type":"default"}} --><div class="wp-block-group t"><!-- wp:paragraph {"className":"k"} --><p class="k">Förderung</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Gefördert von der Stiftung Innovation in der Hochschullehre</h3><!-- /wp:heading --><!-- wp:paragraph --><p><a href="https://stiftung-hochschullehre.de/">stiftung-hochschullehre.de ↗</a></p><!-- /wp:paragraph --></div><!-- /wp:group --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"className":"btn"} --><div class="wp-block-button btn"><a class="wp-block-button__link wp-element-button" href="https://stiftung-hochschullehre.de/">Zur Förderseite <span class="arr">→</span></a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div><!-- /wp:group --></section>
<!-- /wp:group -->
