<?php
/**
 * Title: Katalyst Pillars
 * Slug: katalyst/pillars
 * Categories: katalyst-sections, featured
 * Description: Editable three-pillar section.
 * Viewport Width: 1360
 */
?>
<!-- wp:group {"tagName":"section","anchor":"ansatz","className":"cs bordered","layout":{"type":"default"}} -->
<section id="ansatz" class="wp-block-group cs bordered"><!-- wp:group {"className":"inner","layout":{"type":"default"}} --><div class="wp-block-group inner"><!-- wp:group {"className":"s-head reveal-up","layout":{"type":"flex","verticalAlignment":"center"}} --><div class="wp-block-group s-head reveal-up"><!-- wp:paragraph {"className":"s-num"} --><p class="s-num">02 · Ansatz</p><!-- /wp:paragraph --><!-- wp:heading {"level":2,"className":"s-h"} --><h2 class="s-h">Drei Säulen. Eine Plattform.</h2><!-- /wp:heading --><!-- wp:html --><span class="s-line"></span><!-- /wp:html --></div><!-- /wp:group --><!-- wp:group {"className":"pillars reveal-up","layout":{"type":"default"}} --><div class="wp-block-group pillars reveal-up"><!-- wp:group {"className":"pillar","layout":{"type":"default"}} --><div class="wp-block-group pillar"><!-- wp:html --><div class="mk sq b"></div><!-- /wp:html --><!-- wp:paragraph {"className":"pn"} --><p class="pn">01 — Studierende</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Personalisiertes Lernen</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Lernbegleitung, die auf Vorwissen, Tempo und Ziele reagiert — mit Fokus auf Selbstwirksamkeit und Reflexion.</p><!-- /wp:paragraph --></div><!-- /wp:group --><!-- wp:group {"className":"pillar","layout":{"type":"default"}} --><div class="wp-block-group pillar"><!-- wp:html --><div class="mk qc g"></div><!-- /wp:html --><!-- wp:paragraph {"className":"pn"} --><p class="pn">02 — Lehrende</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Effizientere Materialerstellung</h3><!-- /wp:heading --><!-- wp:paragraph --><p>KI-Werkzeuge, die Lehrende bei Recherche, Aufbereitung und Aktualisierung von Lerninhalten entlasten.</p><!-- /wp:paragraph --></div><!-- /wp:group --><!-- wp:group {"className":"pillar","layout":{"type":"default"}} --><div class="wp-block-group pillar"><!-- wp:html --><div class="mk sq n"></div><!-- /wp:html --><!-- wp:paragraph {"className":"pn"} --><p class="pn">03 — Prüfung</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Transparente Prüfungsformate</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Prüfungsformate, die KI kontrolliert einbinden — fair, nachvollziehbar und für alle Studierenden verfügbar.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group --></div><!-- /wp:group --></section>
<!-- /wp:group -->
